"""Núcleo editorial dos livros PDF: conteúdo, laboratórios e revisão.

O conteúdo é didático e os dados numéricos são sintéticos, calculados pelo
gerador. Métodos comuns são contextualizados por área e pelo tema do volume.
"""
CHAPTERS = [
('Problema, escopo e unidade de análise',[
'Uma análise começa com a definição do objeto, da unidade observada e da decisão que será apoiada. Localização não é um atributo decorativo: ela determina relações de vizinhança, cobertura e suporte. Uma estação mede condições locais; um setor reúne valores de uma área; um pixel registra uma resposta dentro de sua resolução. Resultados obtidos nesses suportes não são intercambiáveis sem uma regra de agregação.',
'Descreva o que está sendo contado, medido ou estimado, em qual período e com quais restrições. Uma pergunta operacional deve indicar destinatário, horizonte, produto e critério de sucesso. A lista de variáveis precisa separar dados disponíveis na decisão, informação derivada e resultado posterior. Usar um dado futuro em um modelo de antecipação torna a avaliação incompatível com o uso real.',
'O contrato de análise também precisa prever a ausência de informação. Sem uma regra explícita, sistemas podem apresentar zero quando não houve observação, misturando falha de coleta e ausência do fenômeno. Declare o significado de cada ausência e o comportamento esperado para amostras vazias, localidades fora da cobertura e períodos incompletos. Essas escolhas afetam o resultado antes de qualquer algoritmo.'
],['A pergunta é verificável e tem destinatário definido?','A unidade espacial e o período estão explicitados?','O produto atende à decisão ou apenas produz uma visualização?']),
('Fontes, metadados e desenho amostral',[
'O inventário deve registrar produtor, endereço de acesso, data de aquisição, versão, licença, tipo de observação, escala ou resolução e referência espacial. Dois arquivos com nomes semelhantes podem representar períodos ou critérios distintos. Preserve a origem e registre um identificador verificável, como hash, para distinguir versões. O hash confirma identidade binária, não precisão ou adequação temática.',
'A distribuição da amostra influencia o que se pode concluir. Pontos concentrados perto de vias podem super-representar áreas acessíveis. Registros administrativos refletem também procedimentos de notificação e atendimento. Um mapa de cobertura ajuda a distinguir concentração real do fenômeno de concentração de coleta. A ausência de registro em uma região pouco observada não demonstra ausência do evento.',
'Defina o papel de cada fonte no fluxo: referência, atributo explicativo, alvo ou validação independente. Uma mesma observação não deve ser reutilizada como prova independente do resultado que ajudou a produzir. Quando fontes possuem datas diferentes, explique a compatibilização ou restrinja a interpretação. Um inventário útil relaciona cada limitação ao efeito esperado no produto, em vez de listar metadados sem uso.'
],['As fontes representam o mesmo período e população?','Há regiões sem suporte amostral?','Qual dado pode servir de avaliação independente?']),
('Referência espacial, escalas e unidades',[
'Um sistema de referência identifica como as coordenadas se relacionam à Terra. Definir o CRS de valores existentes e transformar valores entre CRSs são operações diferentes. Atribuir EPSG:31982 a coordenadas em graus não as converte em metros. Antes da transformação, confira referência de origem, ordem dos eixos, datum, zona, hemisfério e extensão plausível.',
'Cálculos planos de distância e área exigem unidades e projeção adequadas. Latitude e longitude não são metros. Para dados geodésicos, use métodos que tratem a superfície e as unidades explicitamente. SIRGAS 2000 / UTM 22S atende a uma faixa longitudinal específica; não é uma projeção única para todo o Brasil. Altura elipsoidal e altitude vinculada a referência vertical também não são sinônimos.',
'Escala e resolução delimitam o detalhe interpretável. Reamostrar uma imagem para pixels menores não cria informação nova. Agregar observações pode reduzir ruído, mas também esconder variações locais. Declare a unidade de cada indicador e converta somente quando a grandeza permitir. Transformação correta de coordenadas não corrige automaticamente erro de medição ou de identificação da fonte.'
],['As coordenadas são graus ou metros?','A projeção é adequada à região e ao cálculo?','O detalhe da saída é sustentado pela fonte?']),
('Preparação, ausências e consistência',[
'Preparação combina validação de tipos, domínios, chaves, datas e geometrias. Diferencie valor ausente, zero, texto inválido e resultado não aplicável. Converter uma coluna com falhas para número deve produzir um registro de rejeições. Não remova linhas silenciosamente: a distribuição dos registros descartados pode indicar viés regional ou temporal.',
'Uma imputação precisa de hipótese. Mediana reduz sensibilidade a extremos, mas não resolve ausência não aleatória nem preserva variação local. Quando o objetivo envolve previsão, parâmetros de imputação devem ser aprendidos somente no treino e aplicados aos demais conjuntos. Tratar o conjunto inteiro antes de separar treino e teste pode transferir informação de avaliação para o modelo.',
'A validação geométrica individual não equivale à topologia entre feições. Um polígono válido pode se sobrepor indevidamente a outro; uma linha válida pode estar desconectada da rede esperada. Regras dependem do tema e da finalidade. Guarde geometria original, regra aplicada, alteração efetuada e motivo de aceitação antes de substituir um dado em uma base compartilhada.'
],['O tratamento de ausência tem hipótese documentada?','As rejeições alteram a cobertura de dados?','A regra de consistência corresponde ao significado do tema?']),
('Relacionamentos, vizinhança e atributos',[
'Joins relacionam registros por chaves ou predicados espaciais. Antes de unir tabelas, declare a cardinalidade esperada: um para um, um para muitos ou muitos para muitos. Uma junção espacial pode gerar múltiplas correspondências legítimas. Se cada registro expandido for somado como novo evento, os totais serão inflados. Confira contagens e chaves antes e depois de cada operação.',
'Vizinhança representa uma hipótese sobre relação territorial. Contiguidade, raio de distância, k vizinhos e conexão por rede produzem conjuntos diferentes. Um buffer circular representa proximidade geométrica, não tempo de deslocamento. Informe como áreas isoladas, pontos na borda e múltiplas correspondências serão tratados. O predicado contém pode distinguir borda de interior de maneira diferente de cobre.',
'Atributos derivados precisam preservar significado e momento de disponibilidade. Distância a uma infraestrutura, densidade de eventos e resumo por território devem ter unidades, suporte e fonte. Normalização pode facilitar comparação, mas não elimina diferenças de qualidade ou escala. Identificadores quase únicos não devem substituir atributos explicativos: podem permitir memorização sem generalização.'
],['A cardinalidade foi conferida por chave?','A vizinhança representa o processo estudado?','Os atributos estarão disponíveis no momento de aplicação?']),
('Métodos, alternativas e baseline',[
'Um baseline é uma alternativa simples usada como referência. Ele pode ser uma média histórica, persistência temporal, regra explícita ou consulta direta, conforme o problema. Comparar apenas métodos complexos entre si não demonstra benefício sobre uma solução simples. Defina o baseline antes de escolher parâmetros e mantenha condições de avaliação equivalentes.',
'A escolha do método deve considerar hipóteses, unidade de entrada, custo de manutenção e forma de falha. Um resultado visualmente suave pode esconder ausência de suporte; uma classificação de alta acurácia pode ignorar a classe rara. Uma consulta rápida pode responder a uma definição incorreta. Registre o que o método calcula e o que ele não permite concluir, vinculando essas limitações à decisão.',
'Comparações precisam controlar dados, partições e critérios. Não atribua a um algoritmo uma melhora produzida por mudança de amostra ou por acesso a informação adicional. Se houver ajuste de parâmetros, use um conjunto apropriado de validação e preserve teste final. Inclua o esforço operacional: resultado que exige dados indisponíveis ou manutenção inviável pode não atender ao uso pretendido.'
],['O baseline atende à mesma pergunta?','A comparação usa a mesma amostra e o mesmo horizonte?','As hipóteses do método são plausíveis neste território?']),
('Avaliação, métricas e resíduos',[
'Avaliação mede a distância entre o resultado e uma referência independente. Em variável contínua, MAE é a média do erro absoluto e RMSE é a raiz da média do erro quadrático. Ambos mantêm a unidade da variável, mas RMSE dá mais peso a erros grandes. Viés médio preserva sinal e pode revelar superestimação ou subestimação; erros positivos e negativos podem se cancelar.',
'Em classificação, a matriz de confusão organiza classes reais e previstas. Precisão avalia acerto entre positivos previstos; revocação avalia detecção entre positivos reais. Acurácia isolada pode ser alta quando uma classe domina a amostra. Declare qual classe é positiva, limiar, custo dos erros e tratamento de denominadores nulos. Não converta uma pontuação em probabilidade sem avaliar calibração.',
'Métricas agregadas precisam ser acompanhadas de distribuição e localização dos erros. Analise resultados por grupo, período e faixa do indicador. Dependência entre amostras reduz a independência da avaliação; divisões por região ou tempo podem ser mais coerentes com o uso real. Teste o modelo na condição de generalização pretendida, não apenas na condição mais conveniente para obter uma métrica favorável.'
],['A referência é independente do procedimento?','A métrica corresponde à decisão e à unidade?','Onde estão os erros que a média global esconde?']),
('Sensibilidade, incerteza e limites',[
'Uma análise de sensibilidade examina como a saída responde a mudanças controladas de entradas, pesos ou parâmetros. Ela identifica escolhas às quais o resultado é vulnerável. Não equivale automaticamente a um intervalo probabilístico: perturbações arbitrárias não representam distribuição de erro conhecida. Registre a justificativa de cada cenário e mantenha separado o que é hipótese do que foi observado.',
'Incerteza pode vir de medição, cobertura, resolução, modelo e decisão. Intervalos gerados por um método normalmente representam apenas parte dessas fontes. Um intervalo estreito não garante qualidade quando o modelo omite uma fonte dominante de erro. Descreva limites do domínio de aplicação e confira se novas entradas permanecem próximas às condições avaliadas.',
'Apresente cenários comparáveis e a consequência prática de diferenças nos resultados. Para rankings, verifique se pequenas mudanças alteram posições. Para limiares, examine valores próximos ao corte. Para mapas, identifique áreas de baixo suporte. A revisão deve informar quando o produto suporta a decisão, quando exige observações adicionais e quando não deve ser usado naquela finalidade.'
],['A perturbação corresponde a uma fonte de incerteza plausível?','O resultado muda perto de um limiar importante?','Quais erros não estão representados no intervalo apresentado?']),
('Agregação, indicadores e comunicação',[
'Agregação precisa respeitar a natureza da medida. Contagens podem ser somadas quando os eventos são exclusivos; taxas devem preservar numerador e denominador; estoque depende do instante observado. A média simples de taxas de unidades com populações diferentes pode produzir uma interpretação distinta da taxa global ponderada. Documente o grão e os componentes antes de resumir.',
'Mapas, tabelas e gráficos comunicam aspectos complementares. Um mapa coroplético exige cuidado com área territorial e denominadores. Classes de legenda e escala podem destacar ou esconder diferenças; não altere discretização para favorecer uma conclusão. Mostre unidade, período e fonte e ofereça uma tabela para conferência dos valores que o mapa representa.',
'Uma entrega clara separa descrição, interpretação e recomendação. Informe o que foi calculado, em quais condições e com quais limitações. O leitor deve conseguir identificar filtros ativos, dados ausentes e diferenças entre observado e estimado. Acessibilidade requer contraste, símbolos e texto; não dependa apenas de cores para comunicar estados críticos ou classes de informação.'
],['A agregação preserva numeradores e denominadores?','A legenda está coerente com unidade e período?','O destinatário consegue conferir valores e filtros?']),
('Reprodutibilidade, automação e operação',[
'Reprodutibilidade depende de fontes identificadas, parâmetros declarados e ambiente conhecido. Separe dados de origem, intermediários e produtos finais. Registre versão de software, comando de execução, configuração e resultado de validação. Um pipeline deve explicitar o que escreve e evitar sobrescrever a única cópia da fonte.',
'Idempotência significa que repetir a mesma operação, sob as mesmas condições, não deve acumular duplicatas ou alterar resultados indevidamente. Use chaves, transações e gravações controladas. Uma falha intermediária precisa deixar um estado identificável e recuperável. Logs devem relacionar etapa, entrada, saída e erro, sem registrar credenciais ou dados pessoais desnecessários.',
'Operação inclui permissões, monitoramento, atualização e recuperação. Crie perfis de acesso adequados à tarefa, verifique fontes indisponíveis e detecte mudanças de schema. Backup só demonstra recuperação quando uma restauração foi testada. Declare responsável, rotina de revisão e condições de reprocessamento para que o produto não dependa exclusivamente de conhecimento informal de uma pessoa.'
],['Uma execução nova reproduz o produto?','A repetição cria duplicatas ou sobrescreve fontes?','Há procedimento testável para falha e recuperação?']),
('Estudo aplicado e comparação de cenários',[
'O estudo aplicado integra as etapas sem trocar silenciosamente sua pergunta inicial. Defina um conjunto pequeno com resultado verificável antes de usar uma base grande. Os exemplos sintéticos ajudam a conferir cálculo, chaves e unidades, mas não substituem validação temática com observações reais. Registre de forma visível o caráter demonstrativo dos dados.',
'Organize cenários alterando uma hipótese por vez quando a finalidade for interpretar efeitos. Preserve os demais componentes para atribuir diferenças à mudança examinada. Quando variáveis mudarem simultaneamente, trate o resultado como cenário conjunto. Não confunda associação observada, desempenho preditivo e efeito causal de uma intervenção.',
'A conclusão precisa relacionar resultado, critério e limitação. Se o critério não foi atendido, identifique se a causa foi dado insuficiente, método inadequado, implementação ou incompatibilidade com a decisão. Uma execução sem erro de software não comprova validade científica. Apresente evidências que permitam revisão e reconheça situações que exigem coleta adicional ou outro desenho de análise.'
],['O caso mantém a pergunta e a unidade definidas?','As diferenças entre cenários têm hipótese identificada?','A conclusão é proporcional à evidência produzida?']),
('Exercícios integradores e revisão técnica',[
'O exercício integrador deve produzir evidências de todas as decisões importantes: fonte, unidade, preparação, método, avaliação e entrega. Cada exercício precisa ter entrada, procedimento, saída esperada e critério de aceitação. Resultado numérico conhecido facilita identificar erro de implementação; pergunta aberta permite discutir hipóteses e limites que um teste automatizado não avalia.',
'Faça primeiro uma verificação de casos simples, depois examine casos extremos. Inclua amostra vazia, ausência, denominador zero, chave duplicada, coordenada inadequada e mudança de período. Nem toda entrada inválida deve ser corrigida automaticamente. Em vários casos, o comportamento correto é interromper e informar a condição, preservando a fonte para revisão.',
'A revisão deve separar erro de cálculo, escolha de método e interpretação. Se os testes numéricos passarem, ainda será necessário conferir significado dos dados e adequação à decisão. Prepare um relatório curto com procedimento reproduzível, resultados, ressalvas relevantes e próximos passos. A documentação torna as limitações verificáveis e permite melhorar o trabalho em uma execução posterior.'
],['Há critérios de aceitação para os cálculos?','As entradas inválidas são tratadas explicitamente?','O relatório distingue resultado, hipótese e recomendação?']),
]

PROFILES = [
 dict(nome='IA e Machine Learning',foco='alvo, atributos e generalização',objeto='amostra rotulada',metodo='modelo supervisionado',risco='vazamento de informação e dependência entre amostras',
 alternativas=[['Regra ou média de referência','Interpretação simples e baixo custo','Pode ignorar relações importantes'],['Árvores e ensembles','Relações não lineares e interação','Precisam de avaliação independente'],['Redes neurais','Representação aprendida de dados complexos','Exigem dados e controle de treinamento']],
 tarefas=['Defina alvo e a data em que seus atributos estariam disponíveis.','Separe referências de rótulo e fontes de atributos; mapeie sua cobertura.','Confirme suporte do pixel ou unidade territorial antes de associar atributos.','Aprenda imputação somente no treino; documente rótulos ausentes.','Teste joins sem multiplicar rótulos e exclua identificadores que memorizem a resposta.','Compare regra simples, árvore e método do tema em condição equivalente.','Reserve regiões ou cenas e analise matriz de confusão ou resíduos.','Examine estabilidade de previsão e explicação sob mudança plausível de entrada.','Apresente erros por classe e região, junto ao mapa de suporte amostral.','Registre versão do modelo, transformação dos atributos e domínio de aplicação.','Compare uma região conhecida e uma região reservada sem refazer o teste para favorecer o modelo.','Revise erros raros, casos fora do domínio e documentação da decisão.']),
 dict(nome='Geotecnologias',foco='referência espacial, qualidade e produto cartográfico',objeto='feição ou pixel',metodo='processamento geográfico',risco='CRS incorreto, escala incompatível e topologia inadequada',
 alternativas=[['Operação vetorial','Objetos, relações e atributos explícitos','Depende de topologia e precisão'],['Processamento raster','Superfícies e observação por pixel','Depende de resolução e nodata'],['Análise por rede','Conectividade e custo de deslocamento','Não equivale a um buffer euclidiano']],
 tarefas=['Defina produto, área, escala de uso e detalhe necessário.','Inventarie sensor ou vetor, data, licença, precisão e referência.','Diferencie atribuir CRS e transformar coordenadas; revise referência vertical quando aplicável.','Separe validade geométrica, topologia entre feições e ausência temática.','Compare predicados espaciais e trate pontos na borda conforme a regra.','Compare operações vetoriais, raster ou por rede segundo o produto desejado.','Use pontos ou dados independentes e registre erro por região.','Teste resolução, tolerância e suporte, sem inventar detalhe por reamostragem.','Confira simbologia, legenda, escala, unidades e fontes em mapa e tabela.','Preserve fontes e teste projeto ou pacote em outra pasta.','Compare dois parâmetros de processamento e justifique as diferenças observadas.','Revise limites, CRS, integridade e documentação antes da entrega.']),
 dict(nome='BI - Business Intelligence',foco='grão, medidas e decisão',objeto='fato e dimensão territorial',metodo='indicador e modelo semântico',risco='duplicação de fatos, denominador incompatível e filtro ambíguo',
 alternativas=[['Tabela de medidas','Auditoria direta das fórmulas','Maior esforço de leitura'],['Dashboard territorial','Síntese e exploração por filtros','Exige contrato de indicadores'],['Modelo dimensional','Reuso e consistência de medidas','Exige grão e chaves estáveis']],
 tarefas=['Defina destinatário, decisão, indicador e frequência de uso.','Concilie fatos, calendário e versões de limites territoriais.','Confirme unidade do indicador e significado da dimensão territorial.','Trate códigos, datas e nulos sem misturar ausência com zero.','Teste chaves únicas e cardinalidade; fatos não devem se multiplicar em joins.','Compare total, taxa e indicador ponderado, mantendo definição e período.','Confira medidas contra consulta de origem e testes de filtros.','Teste efeitos de pesos, denominadores e período incompleto no resultado.','Mostre numerador, denominador, filtros e data de atualização.','Registre modelo semântico, transformação, rotina de refresh e permissões.','Compare cenários comerciais sem converter pontuação em garantia de retorno.','Revise leitura, filtros, desempenho e rastreabilidade do painel.']),
 dict(nome='Ciência de Dados',foco='distribuição, suporte e inferência',objeto='observação com contexto espacial',metodo='análise estatística e preparação',risco='viés amostral, agregação e hipótese estatística inadequada',
 alternativas=[['Resumo descritivo','Expõe distribuição e ausências','Não demonstra causalidade'],['Análise espacial','Representa vizinhança e suporte','Depende de pesos e escala'],['Modelo estatístico','Formaliza relações e hipóteses','Precisa de diagnóstico e avaliação']],
 tarefas=['Defina população, amostra, variável e suporte da observação.','Examine processo de coleta e cobertura espacial ou temporal.','Registre unidades, CRS e níveis de agregação antes de comparar.','Documente ausência, extremos e decisões de tratamento.','Compare relações por grupo e vizinhança, evitando interpretação ecológica indevida.','Compare resumo robusto, análise espacial e método do tema.','Avalie resíduos, cobertura e independência da referência.','Teste sensibilidade a extremos, grade, pesos e distribuição da amostra.','Combine mapas e distribuições, separando exploração de confirmação.','Preserve código, versões e registro de transformação.','Compare duas hipóteses explicativas e indique o dado que permitiria distingui-las.','Revise hipóteses, limites da inferência e rastreabilidade dos resultados.']),
 dict(nome='Programação para Dados',foco='contratos, funções e execução reproduzível',objeto='registro, arquivo ou resposta de serviço',metodo='rotina de processamento',risco='schema inesperado, erro silencioso e sobrescrita de fonte',
 alternativas=[['Função local','Teste e depuração simples','Exige contratos explícitos'],['Consulta de banco','Processamento próximo aos dados','Depende de schema e índices'],['Serviço ou pipeline','Integração e execução recorrente','Exige controle de falhas e versões']],
 tarefas=['Defina contrato de entrada, saída e efeito permitido da rotina.','Registre arquivos, schema, encoding, versão e permissão de acesso.','Valide CRS e unidades antes de cálculos ou serviços espaciais.','Trate erros, nulos e tipos de maneira explícita e testável.','Verifique cardinalidade de joins e consistência de identificadores.','Compare rotina local, consulta ou serviço pelo mesmo resultado e contrato.','Execute testes conhecidos, entradas vazias e dados inválidos.','Teste timeout, mudança de schema e repetição de execução sem duplicatas.','Documente resultados e mensagens de erro para o usuário da rotina.','Separe configuração e segredo; registre dependências e recuperação.','Compare execução pequena e carga maior, identificando gargalos sem alterar o significado.','Revise segurança de parâmetros, testes e preservação da fonte.']),
 dict(nome='Análise Preditiva',foco='horizonte, suporte e avaliação fora da amostra',objeto='observação histórica e alvo futuro',metodo='previsão ou interpolação',risco='extrapolação, vazamento temporal e métrica otimista',
 alternativas=[['Persistência ou média histórica','Referência simples e verificável','Pode ignorar mudanças do processo'],['Interpolação ou regressão','Relaciona suporte e atributos','Exige hipóteses e avaliação'],['Modelo temporal ou espacial','Representa estrutura específica','Depende de desenho de validação']],
 tarefas=['Defina alvo, horizonte e região de aplicação da previsão.','Separe passado disponível e informação conhecida apenas depois.','Confirme unidade, calendário e distância usados pelo método.','Trate lacunas sem incorporar valores futuros na preparação.','Calcule defasagens e atributos disponíveis no momento de previsão.','Compare baseline e método com o mesmo horizonte e partição.','Avalie blocos ou janelas coerentes com o uso pretendido.','Teste parâmetros e incerteza sem tratar cenário arbitrário como intervalo probabilístico.','Apresente erro por região ou estação e identifique extrapolação.','Registre data de emissão, versão e revisão após novas observações.','Compare cenário de entrada e cenário de método separadamente.','Revise teste final, suporte e condições em que a previsão não é aplicável.']),
]

LAB_EXPLANATIONS = [
('Contrato e inventário','O laboratório representa seis observações sintéticas em coordenadas planas e um indicador genérico. Cada volume utiliza valores próprios para permitir conferir o cálculo. A população de referência é um denominador didático; não é população real de um município. O código separa identificador, grupo, coordenadas, observado e estimativa. No estudo do livro, adapte significado, fonte e unidade desses campos antes de interpretar resultados.','A execução verifica unicidade e valores finitos. Essa verificação não prova representatividade, referência espacial correta ou validade temática. Inclua esses itens em controles separados, com evidências de origem. Para uma base real, um contrato também deve explicar licença, período, domínio, tolerância e conduta em caso de falta de um campo obrigatório.'),
('Perfil de dados e cobertura','O resumo por grupo revela quantidade, distribuição e suporte. Os grupos representam áreas didáticas A, B e C, não recortes administrativos reais. Uma média por grupo pode ser igual mesmo quando cobertura, dispersão ou denominadores são diferentes. A tabela permite relacionar estatística e amostra antes de transformar valores ou escolher método.','Não extrapole o perfil de seis registros a uma população. Em uso real, examine processo de seleção, tamanho dos grupos e cobertura em mapa. Estatística computada corretamente ainda pode descrever uma amostra enviesada. O produto deste laboratório é uma conferência do procedimento e uma lista de limitações para o tema do volume.'),
('Distância e escala','As coordenadas do laboratório são planas, em metros, com referência local didática. A expressão raiz de delta E ao quadrado mais delta N ao quadrado calcula distância horizontal no plano. Não aplica correção de projeção, distância de terreno ou deslocamento por rede. O azimute começa no norte e cresce no sentido horário; pontos coincidentes não definem direção.','Compare esses valores apenas dentro do sistema indicado. Em longitude e latitude, o mesmo código não produz metros. Para dados reais, escolha cálculo geodésico ou projeção adequada e documente transformação. Em análise de acesso, distância euclidiana é um baseline; tempo de viagem exige rede, modo e condições operacionais.'),
('Tratamento de ausência','O exemplo introduz uma ausência em um atributo numérico e calcula a mediana a partir dos demais valores. A regra é determinística e pode ser conferida manualmente. A linha com ausência permanece identificada, permitindo distinguir dado original e valor tratado. Não há alegação de que a mediana seja sempre a melhor hipótese para o tema.','A ausência pode depender de localização, período ou processo de coleta. Substituí-la por um único número pode reduzir variabilidade e alterar relações. Em modelagem, calcule o parâmetro somente no treino. Em indicadores oficiais, avalie se imputação é permitida ou se a saída deve ser marcada como indisponível. Registre a decisão e seu impacto.'),
('Relação e vizinhança','O código enumera vizinhos dentro de um raio fixo em coordenadas planas. A relação inclui a borda por usar comparação menor ou igual. Cada identificador aparece uma vez na origem, mas pode ter vários vizinhos; somar registros da lista de relações como novos eventos seria incorreto. O raio tem unidade em metros e uma finalidade de demonstração.','Uma vizinhança por distância difere de contiguidade ou conexão por rede. Compare a regra com a pergunta do caso. Para tabelas grandes, use índice ou estrutura adequada; o laço completo é uma referência simples de complexidade quadrática. Não confunda teste de igualdade geométrica com deduplicação de objetos distintos no mesmo endereço.'),
('Baseline e comparação','Duas alternativas são avaliadas sobre os mesmos valores: média do conjunto e estimativa sintética fornecida na tabela. O resultado da estimativa foi construído apenas para estudar métricas; ele não vem de um modelo treinado nem de um levantamento. Portanto, a comparação é uma demonstração de cálculo, não evidência de superioridade de algoritmo.','Em avaliação real, a média de baseline deve ser aprendida no treino e aplicada ao teste. Usar a média de todo o teste como método comparativo pode fornecer informação indisponível na operação. Registre partição, horizonte, referência e hipótese do baseline. A alternativa simples precisa atender à mesma pergunta do método principal.'),
('Métricas e resíduos','O código calcula erro como estimado menos observado, MAE, RMSE e viés. Os denominadores são o número de observações válidas. O erro absoluto mantém magnitude; o quadrático dá maior peso a discrepâncias grandes; o viés mantém sinal. A tabela por registro ajuda a localizar erros que se cancelam na média.','Essas métricas são adequadas a valores contínuos comparáveis na mesma unidade. Para classes ou probabilidades, adapte avaliação ao alvo: matriz de confusão, métricas de detecção ou calibração. Não selecione a métrica depois de ver qual produz a melhor narrativa. Defina o critério em função da decisão e examine desempenho por grupo.'),
('Perturbação e sensibilidade','O laboratório altera a estimativa por menos dez por cento, valor original e mais dez por cento. Os cenários tornam explícito que uma escolha de entrada ou parâmetro pode modificar erro e viés. As três perturbações são hipóteses didáticas, não quantis de uma distribuição de incerteza conhecida.','Não chame a amplitude dos cenários de intervalo de confiança. Para inferência probabilística, é necessário um modelo de erro e um procedimento adequado. Observe se o resultado atravessa limiares da decisão e se a mudança é consistente entre grupos. Explicar o mecanismo da alteração é mais útil que apresentar apenas uma faixa numérica.'),
('Agregação e taxa','O exercício compara média simples das taxas e taxa do total. A primeira dá o mesmo peso a cada registro; a segunda soma numeradores e denominadores compatíveis. Os denominadores foram construídos para evidenciar a diferença. Uma taxa deve informar sua base, como por cem unidades, e o período a que os componentes se referem.','O indicador genérico do laboratório não é automaticamente uma contagem de eventos; a taxa aqui é uma operação aritmética de estudo. Em base real, confirme que o numerador e a população em risco permitem essa razão. Não some estoques de instantes diferentes nem taxas já normalizadas como se fossem contagens exclusivas.'),
('Manifesto e reprodução','Um manifesto registra nome do volume, parâmetros e hash dos dados serializados em ordem definida. Isso permite identificar o conjunto utilizado e repetir cálculos. JSON com chaves ordenadas evita diferenças apenas de ordem dos campos; o hash muda se qualquer valor ou representação relevante mudar.','O manifesto não substitui fonte autorizada, contrato de schema ou registro de ambiente. Uma execução reproduzível inclui versão de dependências e conduta em erros. Não grave segredos nem dados pessoais desnecessários nos logs. Para cargas em banco ou serviços, acrescente transação, política de repetição e estado de recuperação.'),
('Cenário com grupo reservado','O código reserva o grupo C e calcula um baseline com os grupos A e B. O desenho imita a ideia de aplicar um procedimento a um grupo não usado para ajustar o parâmetro. O conjunto pequeno permite calcular manualmente a média de treino e o erro do grupo reservado, sem confundir aprendizado e avaliação.','Esse exemplo não estabelece independência espacial real nem poder estatístico: os grupos e valores são sintéticos. Em um estudo, escolha bloco ou período pela escala do processo e mantenha teste final fora das escolhas de modelo. Se o teste for consultado repetidamente para escolher parâmetros, ele deixa de ser uma avaliação final independente.'),
('Testes e revisão','Os testes verificam cálculo, entrada vazia e coerência da identidade dos registros. Casos conhecidos são úteis para detectar regressões em rotinas. Valores iguais produzem erro zero; uma previsão deslocada por duas unidades tem MAE de duas unidades. O código rejeita listas incompatíveis, evitando uma comparação silenciosa de observações erradas.','Testes numéricos não avaliam sozinhos precisão da fonte, hipótese científica ou interpretação. Separe revisão automática e revisão temática. Acrescente entradas específicas do assunto do livro e documente resultados observados. O exercício final exige um relatório que conecte método, evidência, limitações e ação proposta.'),
]
